on:
  push:
    branches:
      - master        





jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v3


      - name: "Login to DockerHub"
        run: docker login --username hagersaad615@gmail.com --password dckr_pat_V7L4h6ImdgqmcKqPL4dPkjeWcKc
